disabled_rules: # rule identifiers to exclude from running
  - trailing_whitespace
  - line_length
  - vertical_whitespace
  - opening_brace
#  - comma
  - todo
  - type_name
  - function_parameter_count
  - cyclomatic_complexity
#  - file_length
#  - function_body_length
#  - type_body_length
#  - variable_name

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - AnyReadTests
