//
//  MyStyleKit.h
//  ProjectName
//
//  Created by AuthorName on 27.10.16.
//  Copyright © 2016 CompanyName. All rights reserved.
//
//  Generated by PaintCode
//  http://www.paintcodeapp.com
//

#import <UIKit/UIKit.h>


@interface MyStyleKit : NSObject

// Drawing Methods
+ (void)drawBubbleButtonWithFrame: (CGRect)frame;

@end
